### ISSUE TITLE
Octave 7.x and 8.x support in formulae

### ISSUE THREAD

**Issue by apjanke** [octave-app/homebrew-octave-app#7]
This ticket is to track all the things needed to get Octave 7.x and 8.x building in an Octave.app build environment.

## Work streams

* I'm doing my work on this `new-2023-versions` branch.
  * https://github.com/octave-app/homebrew-octave-app/tree/new-2023-versions

## TODO

* [x] New formulae for the Octave 7.x and 8.x versions, both regular versioned `octave` formulae, and `octave-octave-app` formulae.
* [X] Bump and update all the special `*-octave-app` formulae.
  * [X] Replace "-octave-app" suffix with "-octapp".
* [x] Get 'em all building on macOS 12 and 14, and on Apple Silicon.
  * 2024-01-16: builds on macOS 14 Intel and AS are working. Had a couple good macOS 12 builds; need to test that more next.

**Comment by apjanke** [comment]
I've got an 8.3.0 non-octapp-ified formula that's building. Working on getting all the octapp formulae building.

On macOS 12 in a VM (monty_p), `brew install gnuplot-octave-app` is failing for me with the bumped gnuplot-octave-app 5.4.1.0 formula, with the following build error (from `01.make` in the brew logs):

```
clang++  -std=c++17 -fPIC   -L/usr/local/Cellar/libcerf/2.4/lib -lcerf -L/usr/local/opt/readline/lib  -o gnuplot alloc.o axis.o breaders.o boundary.o color.o command.o contour.o datablock.o datafile.o dynarray.o encoding.o eval.o external.o fit.o gadgets.o getcolor.o graph3d.o graphics.o help.o hidden3d.o history.o internal.o interpol.o jitter.o libcerf.o matrix.o misc.o mouse.o multiplot.o parse.o plot.o plot2d.o plot3d.o pm3d.o readline.o save.o scanner.o set.o show.o specfun.o standard.o stats.o stdfn.o tables.o tabulate.o term.o time.o unset.o util.o util3d.o variable.o version.o voxelgrid.o vplot.o xdg.o  wxterminal/gp_cairo.o wxterminal/gp_cairo_helpers.o  qtterminal/qt_term.o -lreadline  -lncurses  -lz -lgd -L/usr/local/Cellar/gd/2.3.3_6/lib -lgd -L/usr/local/lib -llua -lm   -F/usr/local/opt/qt-octave-app/Frameworks -framework QtCore -framework QtGui -framework QtNetwork -framework QtSvg -framework QtPrintSupport -framework QtWidgets -framework QtCore5Compat -liconv  -L/usr/local/Cellar/glib/2.78.1/lib -L/usr/local/opt/gettext/lib -L/usr/local/Cellar/cairo/1.18.0/lib -L/usr/local/Cellar/harfbuzz/8.2.2/lib -L/usr/local/Cellar/pango/1.50.14/lib -lz -lpangocairo-1.0 -lpango-1.0 -lgobject-2.0 -lharfbuzz -lcairo -lglib-2.0 -lintl
ld: framework not found QtCore5Compat
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[4]: *** [gnuplot] Error 1
make[3]: *** [all-recursive] Error 1
make[2]: *** [all] Error 2
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2

HOMEBREW_VERSION: 4.1.17-39-g700c7de
ORIGIN: https://github.com/Homebrew/brew
HEAD: 700c7dea3f977e0e6e8c9fffcddc9f3fa2ca0994
Last commit: 8 hours ago
Core tap JSON: 29 Oct 03:46 UTC
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_DEVELOPER: set
HOMEBREW_EDITOR: subl
HOMEBREW_MAKE_JOBS: 1
HOMEBREW_NO_AUTO_UPDATE: set
HOMEBREW_NO_BOOTSNAP: set
HOMEBREW_SORBET_RUNTIME: set
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: dodeca-core 64-bit skylake
Clang: 14.0.0 build 1400
Git: 2.42.0 => /usr/local/bin/git
Curl: 8.1.2 => /usr/bin/curl
macOS: 12.7.1-x86_64
CLT: 14.2.0.0.1.1668646533
Xcode: 14.2
```

I don't know what QtCore5Compat is, or why it's being used or failing here.

**Comment by apjanke** [comment]
Hmm. There was this section in the gnuplot-octave-app formula:

```
    qtlibs = %W[-F#{Formula["qt-octave-app"].opt_prefix}/Frameworks]
    %w[Core Gui Network Svg PrintSupport Widgets QtCore5Compat].each do |m|
```

...so I tried removing the "QtCore5Compat" item from it.

Now I'm getting this build error:

```
clang  -g -O2  -L/usr/local/Cellar/libcerf/2.4/lib -lcerf -L/usr/local/opt/readline/lib  -o bf_test bf_test.o -lm
/usr/local/opt/qt-octave-app/share/qt-octave-app/libexec/uic -o ui_QtGnuplotSettings.h qtterminal/QtGnuplotSettings.ui
make[4]: /usr/local/opt/qt-octave-app/share/qt-octave-app/libexec/uic: No such file or directory
make[4]: *** [ui_QtGnuplotSettings.h] Error 1
make[3]: *** [all-recursive] Error 1
make[2]: *** [all] Error 2
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2
```

**Comment by apjanke** [comment]
Getting further. Now the 8.3.0 build is bonking at the create_dmg stage.

```
Savings: 76.4%
created: /Users/janke/repos/octave-app-bundler/build/Octave-8.3.0-alpha1.dmg
adding EULA resources
env: python: No such file or directory
janke@monty-p:~/repos/octave-app-bundler $ which python
python not found
```

That looks like a shebang in a script calling `#!/bin/env python`, and there's no `python` available by default in macOS 12 and later; it's `python3` now.

**Comment by apjanke** [comment]
I'm satisfied the 8.x fortmulae are working now. Octave 9.0 is almost out now, so having 7.x builds is not a priority now; I'll maybe handle that under a separate ticket some day. Closing this as Fixed.
